### ISSUE TITLE
0.8.7 error on 2nd HDT run

### ISSUE THREAD

**Issue by maxapasov** [batstyx/Hearthstone-Collection-Tracker#1]
Hi. Thx for update. But on 2nd run HDT error:

Make sure you are using the latest version of the Plugin and HDT.

System.Exception: File with your collection information is corrupted. ---> System.NullReferenceException: Object reference not set to an instance of an object.
at Hearthstone_Collection_Tracker.SetCardsManager.<>c__DisplayClass2_0.b__0(Card c)
at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
at Hearthstone_Collection_Tracker.SetCardsManager.LoadSetsInfo(String collectionStoragePath)
--- End of inner exception stack trace ---
at Hearthstone_Collection_Tracker.SetCardsManager.LoadSetsInfo(String collectionStoragePath)
at Hearthstone_Collection_Tracker.Internal.PluginSettings.SetActiveAccount(String accountName, Boolean forceReload)
at Hearthstone_Collection_Tracker.Internal.PluginSettings.LoadSettings(String dataDir)
at Hearthstone_Collection_Tracker.HearthstoneCollectionTrackerPlugin.OnLoad()
at Hearthstone_Deck_Tracker.Plugins.PluginWrapper.Load() in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Plugins\PluginWrapper.cs:line 91

**Comment by batstyx** [comment]
Hi,
Unfortunately this is an issue with v1.8.4 of HDT. You'll either have to downgrade back to HDT v1.8.3 or wait for a fixed release of HDT. You shouldn't need to downgrade the plugin but it'll show an empty section for Rise of Shadows in earlier HDT versions.

The cause is the cards joining the Hall of Fame next week temporarily missing their Set value.
You can test this in HDT by looking at a deck containing one of these cards (e.g. Naturalize, Doomguard etc). The tooltip will be missing the Set value below the Card Type.
The CardDefs.xml file from https://github.com/HearthSim/hsdata this data comes from was corrected this morning but I don't know when a new release of HDT will turn up.

**Comment by batstyx** [comment]
For example: 

![image](https://user-images.githubusercontent.com/6762496/55675016-38188780-58b4-11e9-930c-9eafb3e31e6e.png)

**Comment by maxapasov** [comment]
Thx! Understand. Waiting HDT update.
